### ISSUE TITLE
Cant Install

### ISSUE THREAD

**Issue by theavijitsarkar** [jayrathod/Cordova-Cell-Triangulation#1]
```
 cordova plugin add https://github.com/jayrathod/Cordova-Cell-Triangulation.git
Fetching plugin "https://github.com/jayrathod/Cordova-Cell-Triangulation.git" via git clone
Repository "https://github.com/jayrathod/Cordova-Cell-Triangulation.git" checked out to git ref "master".
Error: ENOENT: no such file or directory, open '/var/folders/w1/186ymwl94cj7q24ld4v284mw0000gn/T/git/1452280671824/plugin.xml'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.module.exports.parseElementtreeSync (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/util/xml-helpers.js:118:27)
    at new PluginInfo (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/PluginInfo.js:320:37)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/plugins.js:45:30
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:557:44

```

**Comment by roysG** [comment]
Same problem.

$ cordova plugin add https://github.com/jayrathod/Cordova-Cell-Triangulation.git

Fetching plugin "https://github.com/jayrathod/Cordova-Cell-Triangulation.git" via git clone
Repository "https://github.com/jayrathod/Cordova-Cell-Triangulation.git" checked out to git ref "master".
Failed to fetch plugin https://github.com/jayrathod/Cordova-Cell-Triangulation.git via git.
Either there is a connection problems, or plugin spec is incorrect:
    CordovaError: Cannot find plugin.xml for plugin '1458685982836'. Please try adding it again.

**Comment by roysG** [comment]
any news?

**Comment by AtulaGuleria** [comment]
owner hasn't attached the plugin.xml file.
that why we are unable to install it.

**Comment by AizatRafee** [comment]
same problem.

Error: Failed to fetch plugin https://github.com/jayrathod/Cordova-Cell-Triangulation.git via git.
Either there is a connection problems, or plugin spec is incorrect:
        Cannot find plugin.xml for plugin "1491888451545". Please try adding it again.
